sonar.projectKey=samuelv-tasklist-frontend
sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr

sonar.sources=src
sonar.exclusions=src/__tests__/**,src/main.tsx,src/vite-env.d.ts
sonar.test.inclusions=src/__tests__/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
